package com.projectxy.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "accounts")
public class Account {
	// An autogenerated id (unique for each user in the db
	private int id;
	private String userName;
	private String firstName;
	private String lastName;
	private String email;

	
	public Account(){}
	
	public Account(int id){
		this.id = id;
	}
	public Account(int id, String userName, String name, String email) {
		this.id = id;
		this.userName = userName;
		this.firstName = name;
		this.email = email;
	}

	@GeneratedValue
	@Id
	@Column(name = "id")
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String name) {
		this.firstName = name;
	}
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "{\"id\": \"" + id + "\", \"userName\":\"" + userName + "\", \"name\":\"" + firstName + " "+ lastName + "\", \"email\":\""
				+ email + "\", \"lastName\":\"" + lastName + "\"}";
	}

}
